#!/usr/bin/env bash

LEDGER_FILE="$HOME/masher.ldg"

tengo() {
    case $1 in 
        bs|bdv) account='Banco de Venezuela';;
        pp|paypal) account='Assets:PayPal';;
        uh|uphold) account='Assets:Uphold:Expendable';;
        ahorrado) account='Assets:Uphold:Emergency';;
        *) exit 1;;
    esac

    ledger_result=$(ledger -f $LEDGER_FILE balance --real --no-total "$account")
    amount=$(echo "$ledger_result" | sed -n -E 's/^\s*\$?([0-9.]+).*/\1/p')
    espeak -v spanish "$amount"
}

# Run any of the functions defined before
"$@"
